export const SET_PENSION_DATA = "SET_PENSION_DATA";
export const REMOVE_PENSION_DATA = "REMOVE_PENSION_DATA";
export const SET_EMPLOYMENT = "SET_EMPLOYMENT";
export const SET_CUSTOM_DATA = "SET_CUSTOM_DATA";
export const SET_PARTICIPANT_DATA = "SET_PARTICIPANT_DATA";
export const SET_PARTICIPANT_PROFILE = "SET_PARTICIPANT_PROFILE";
export const SET_PRODUCT_DATA= "SET_PRODUCT_DATA";
export const SET_ALL_PARTICIPANTS= "SET_ALL_PARTICIPANTS";
