export const SET_PENSION_DATA = "SET_PENSION_DATA";
export const REMOVE_PENSION_DATA = "REMOVE_PENSION_DATA";
export const SET_EMPLOYMENT = "SET_EMPLOYMENT";
export const SET_CUSTOM_DATA = "SET_CUSTOM_DATA";
